config/routes.rb
Rails.application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root 'games#index'

  resources :teams

  resources :invitations do
    post 'accept', on: :member
    post 'reject', on: :member
  end

  resources :team_requests do
    post 'accept', on: :member
    post 'reject', on: :member
  end

  resources :users do
    resources :games
  end

  resources :games do
    resources :levels do
      resources :tasks
      resources :hints do
        post 'copy', on: :member
      end
      resources :penalty_hints do
        post 'copy', on: :member
      end
      resources :questions do
        resources :answers
        collection do
          get  :new_batch
          post :create_batch
        end
        post 'move_up', on: :member
        post 'move_down', on: :member
        post 'copy', on: :member
        post 'copy_to_bonus', on: :member
      end
      resources :bonuses do
        resources :bonus_answers
        collection do
          get  :new_batch
          post :create_batch
        end
        post 'move_up', on: :member
        post 'move_down', on: :member
        post 'copy', on: :member
        post 'copy_to_sector', on: :member
      end
      resources :messages
      collection do
        patch :sort
      end
      post 'move_up', on: :member
      post 'move_down', on: :member
      post 'change_position', on: :member
      post 'copy', on: :member
      post 'dismiss', on: :member
      post 'undismiss', on: :member
      post 'add_answer_to_sectors', on: :member
      post 'add_answer_to_bonuses', on: :member
    end
    resources :game_bonuses
    get 'show_scenario', on: :member
    get 'new_level_order', on: :member
    post 'create_level_order', on: :member
    post 'end_game', on: :member
    post 'open_game', on: :member
    post 'start_test', on: :member
    post 'finish_test', on: :member
  end

  match '/game_entries/recall/:id', to: 'game_entries#recall', via: 'post'
  match '/game_entries/reopen/:id', to: 'game_entries#reopen', via: 'post'
  match '/game_entries/cancel/:id', to: 'game_entries#cancel', via: 'post'
  match '/game_entries/accept/:id', to: 'game_entries#accept', via: 'post'
  match '/game_entries/reject/:id', to: 'game_entries#reject', via: 'post'
  match '/game_entries/reaccept/:id', to: 'game_entries#reaccept', via: 'post'
  match '/game_entries/new/:game_id/:team_id',  to: 'game_entries#new', via: 'post'

  match '/game_passings/show_results', to: 'game_passings#show_results', via: 'get'
  match '/play/:game_id/tip', to: 'game_passings#get_current_level_tip', via: 'get'
  match '/play/:game_id', to: 'game_passings#show_current_level', via: 'get'
  match '/play/:game_id', to: 'game_passings#post_answer', via: 'post'
  match '/play/:game_id/autocomplete_level', to: 'game_passings#autocomplete_level', via: 'get'
  match '/play/:game_id/penalty_hint', to: 'game_passings#use_penalty_hint', via: 'post'
  match '/play/:game_id/penalty_hint', to: 'game_passings#show_penalty_hint', via: 'get'
  match '/play/:game_id/bonus', to: 'game_passings#get_current_level_bonus', via: 'get'
  match '/play/:game_id/miss_bonus', to: 'game_passings#miss_current_level_bonus', via: 'post'

  match '/stats/:action/:game_id', to: 'game_passings#index', via: 'get'
  match '/logs/livechannel/:game_id', to: 'logs#show_live_channel', via: 'get'
  match '/logs/level/:game_id/:team_id', to: 'logs#show_level_log', via: 'get'
  match '/logs/game/:game_id/:team_id', to: 'logs#show_game_log', via: 'get'
  match '/logs/full/:game_id', to: 'logs#show_full_log', via: 'get'
  match '/logs/short/:game_id', to: 'logs#show_short_log', via: 'get'
  match '/logs/special/:game_id', to: 'logs#show_special_results', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/dashboard', to: 'dashboard#index',         via: 'get'
  match '/team-room', to: 'team_room#index',         via: 'get'

  match '/teams/edit/delete_member', to: 'teams#delete_member', via: 'post'
  match '/teams/edit/captain', to: 'teams#make_member_captain', via: 'post'
  match '/teams/edit/leave_team', to: 'teams#leave_team', via: 'post'
  match '/tinymce_assets', to: 'tinymce_assets#create', via: 'post'
  match '/help', to: 'help#index', via: 'get'
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :game_entries, class_name: 'GameEntry'
  has_many :members, class_name: 'User'
  belongs_to :captain, class_name: 'User'
  has_many :tasks
  has_many :hints
  has_many :penalty_hints
  has_many :questions
  has_many :answers
  has_many :level_orders
  has_many :game_bonuses, class_name: 'GameBonus'
  has_many :results

  scope :by_name, ->(name) { where('lower(name) = ?', name) }

  validates_uniqueness_of :name, scope: :team_type, message: 'Команда з такою назвою уже існує'

  validates_presence_of :name, message: 'Назва команди не повинна бути порожньою', on: :create

  before_save :adopt_captain

  def current_level_in(game)
    game_passing = GamePassing.of(id, game.id)
    game_passing.try(:current_level)
  end

  def finished?(game)
    game_passing = GamePassing.of(id, game.id)
    !!game_passing.try(:finished?)
  end

  protected

  def adopt_captain
    members << captain unless captain.nil? || members.include?(captain)
  end
end

app/controllers/game_passings_controller.rb
require 'ee_strings.rb'

class GamePassingsController < ApplicationController
  include GamePassingsHelper

  before_action :authenticate_user!, except: [:index, :show_results]
  before_action :find_game, except: [:exit_game]
  before_action :find_game_by_id, only: [:exit_game]
  before_action :ensure_user_has_team, only: [:show_current_level, :get_current_level_tip, :post_answer, :autocomplete_level, :penalty_hint, :get_current_level_bonus, :miss_current_level_bonus]
  before_action :find_team, except: [:show_results, :index]
  before_action :find_team_id, only: [:show_current_level, :get_current_level_tip, :post_answer, :autocomplete_level, :penalty_hint, :get_current_level_bonus, :miss_current_level_bonus]
  before_action :ensure_team_is_accepted, except: [:show_results, :index]
  before_action :ensure_game_is_started
  before_action :ensure_not_author_of_the_game, except: [:index, :show_results]
  before_action :find_or_create_game_passing, except: [:show_results, :index]
  before_action :ensure_team_captain, only: [:exit_game]
  before_action :ensure_not_finished, except: [:index, :show_results]
  before_action :author_finished_at, except: [:index, :show_results]
  before_action :ensure_team_member, except: [:index, :show_results]
  before_action :ensure_author, only: [:index]

  def show_current_level
    time = Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time
    respond_to do |format|
      if @game_passing.finished_at.nil? && !(@game.game_type == 'panic' && (@game.starts_at + @game.duration * 60) < time)
        @level = if @game.game_type == 'panic'
                   params[:level] ? @game.levels.where(position: params[:level]).first : @game.levels.first
                 else
                   @game_passing.current_level
                 end
        @entered_all_answers = get_uniq_level_codes(@level)
        @bonuses = get_answered_bonuses(@level)
        @sectors = get_answered_questions(@level)
        @penalty_hints = get_penalty_hints(@level)
        @upcoming_hints = @game_passing.upcoming_hints(@team_id, @level)
        @hints_to_show = @game_passing.hints_to_show(@team_id, @level)
        format.html do
          render layout: 'in_game', locals: {
              game_passing: @game_passing,
              game: @game,
              team_id: @team_id,
              level: @level,
              entered_all_answers: @entered_all_answers,
              bonuses: @bonuses,
              sectors: @sectors,
              penalty_hints: @penalty_hints,
              upcoming_hints: @upcoming_hints,
              hints_to_show: @hints_to_show,
              answer: @answer
          }
        end
        format.json do
          level_position = @game.game_type == 'selected' ? @game_passing.current_level_position(@team_id) : @level.position
          all_sectors = @level.team_questions(@team_id)
          sectors_count = all_sectors.count
          level_time =  if @game.game_type == 'panic'
                          (@level.complete_later || 0).zero? ? @game.duration * 60 : @level.complete_later
                        else
                          @level.complete_later || 0
                        end
          level_start = level_position == 1 || @game.game_type == 'panic' ? @game.starts_at : @game_passing.current_level_entered_at
          hint_num = 0
          current_level_json = {
              game: {id: @game.id, name: @game.name, levels_count: @game.levels.count, game_type: @game.game_type},
              team: {id: @team.id, name: @team.name},
              level: {
                  id: @level.id,
                  name: @level.name,
                  position: level_position,
                  autocomplete_time: level_time,
                  left_time: level_time == 0 ? 0 : (level_start - time).to_i + level_time,
                  sectors_count: sectors_count,
                  sectors_need: @level.sectors_for_close.zero? ? sectors_count : @level.sectors_for_close,
                  sectors_closed: @game.game_type == 'panic' ? @game_passing.questions.count : (@game_passing.question_ids.to_set & all_sectors.map(&:id).to_set).count,
                  tasks: @level.team_tasks(@team_id).map { |task| {id: task.id, text: task.text} },
                  messages: @level.messages.map { |message| { user: message.user_nickname, text: message.text} },
                  hints: @hints_to_show.map do |hint|
                    hint_num += 1
                    {
                      id: hint.id,
                      number: hint_num,
                      text: hint.text,
                      time_to_hint: 0
                    }
                  end + @upcoming_hints.map do |hint|
                    hint_num += 1
                    {
                      id: hint.id,
                      number: hint_num,
                      text: '',
                      time_to_hint: hint.available_in(level_start)
                    }
                  end,
                  penalty_hints: @penalty_hints.map do |hint|
                    {
                      id: hint[:id],
                      name: hint[:name],
                      penalty: hint[:penalty] || 0,
                      used: hint[:used],
                      text: hint[:used] ? hint[:text] : ''
                    }
                  end,
                  sectors: @sectors.map do |sector|
                    {
                      id: sector[:id],
                      position: sector[:position],
                      name: sector[:name],
                      answered: sector[:answered],
                      answer: sector[:answered] ? sector[:answer] : ''
                    }
                  end,
                  bonuses: @bonuses.map do |bonus|
                    {
                        id: bonus[:id],
                        name: bonus[:name],
                        answered: bonus[:answered],
                        help: bonus[:answered] ? bonus[:help] : '',
                        award: bonus[:answered] ? bonus[:award] : 0,
                        answer: bonus[:answered] ? bonus[:value] : '',
                        missed: bonus[:missed],
                        delayed: bonus[:delayed] && !bonus[:missed],
                        delay_for: bonus[:delayed] && !bonus[:missed] ? bonus[:delay_for] : 0,
                        limited: bonus[:limited] && !bonus[:missed] && !bonus[:answered] && (!bonus[:delayed] || bonus[:delay_for].zero?),
                        valid_for: bonus[:limited] && !bonus[:answered] && !bonus[:missed] ? bonus[:valid_for] : 0,
                        task: bonus[:answered] || bonus[:missed] || bonus[:delayed] ? '' : bonus[:task]
                    }
                  end
              }
          }

          render json: current_level_json
        end
      else
        format.html { redirect_to game_passings_show_results_url(game_id: @game.id) }
        format.json { render json: {status: 'ok', message: 'game finished'} }
      end
    end
  end

  def index
    @game_passings = GamePassing.of_game(@game.id)
    render
  end

  def get_current_level_tip
    level_id = params[:level_id]
    level = Level.find(level_id)
    upcoming_hints_count = @game_passing.upcoming_hints(@team_id, level).count
    hints_to_show = @game_passing.hints_to_show(@team_id, level)
    hint_to_show_count = hints_to_show.count
    last_hint = hints_to_show.last

    render json: { hint_num: hint_to_show_count,
                   hint_text: (hint_to_show_count == 0 ? '' : last_hint.text.html_safe),
                   hint_id: (hint_to_show_count == 0 ? nil : last_hint.id),
                   hint_count: hint_to_show_count + upcoming_hints_count
                 }
  end

  def get_current_level_bonus
    level_id = params[:level_id]
    level = Level.find(level_id)
    bonus_id = params[:bonus_id]
    bonus = level.bonuses.find(bonus_id)
    current_level_entered_at = level.position == 1 || @game_passing.game_type == 'panic' ? level.game_starts_at : @game_passing.current_level_entered_at
    current_time = Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time
    if !bonus.nil? && !bonus.is_delayed_now?(current_level_entered_at, current_time)
      render json: {
        bonus_num: bonus.position,
        bonus_name: bonus.name,
        bonus_task: bonus.task,
        bonus_id: bonus.id,
        bonus_limited: bonus.is_limited_now?(current_level_entered_at, current_time),
        bonus_valid_for: bonus.time_to_miss(current_level_entered_at, current_time)
      }
    else
      render json: {}
    end
  end

  def miss_current_level_bonus
    level_id = params[:level_id]
    level = Level.find(level_id)
    bonus_id = params[:bonus_id]
    bonus = level.bonuses.find(bonus_id)
    @game_passing.miss_bonus!(level_id, bonus.id)

    render json: {bonus_id: bonus.id, bonus_name: bonus.name}
  end

  def post_answer
    time = Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time
    if @game_passing.finished? ||
       @game.game_type == 'panic' &&
       @game.starts_at + 60 * @game.duration < time
      respond_to do |format|
        # format.html { redirect_to game_passings_show_results_url(game_id: @game.id) }
        format.js
      end
    else

      level = @game.game_type == 'panic' ? @game.levels.find(params[:level_id]) : @game_passing.current_level
      if (level == @game_passing.current_level || @game.game_type == 'panic') && !level.complete_later.nil? && level.complete_later > 0
        begin
          time_start = level.position == 1 || @game.game_type == 'panic' ? @game.starts_at : @game_passing.current_level_entered_at
          time_finish = time_start + level.complete_later
          if time > time_finish
            save_log(level, time_finish, 3)
            @game_passing.autocomplete_level!(level, @team_id, time_start, time_finish, current_user.id)
            respond_to do |format|
              # format.html do
              #   redirect_to 'show_current_level'
              # end

app/helpers/game_passings_helper.rb
module GamePassingsHelper
  def answer_posted?
    !@answer.nil?
  end

  def answer_was_correct?
    !!@answer_was_correct
  end

  def game_levels_list(game)
    game.levels.map do |game_level|
      if game_level == @level
        "#{game_level.position}. #{game_level.name}"
      else
        "<a class=\"#{(@game_passing.closed?(game_level) ? 'closedlevel' : 'openedlevel')}\" href=\"/play/#{game.id}?level=#{game_level.position}\">#{game_level.position}. #{game_level.name}</a>"
      end
    end.join(', ')
  end
end

app/views/game_passings/_bonuses.html.erb
<div id="LevelBonusesContainer">
  <ul>
    <% bonuses.each do |bonus| %>
        <li id="bonus-<%= bonus[:id] %>">
          <% if bonus[:answered] %>
            <p class="bonus-answered">
              <b>
                <% if (bonus[:award] || 0) > 0 %>
                  <%= "#{bonus[:name]}: нагорода #{seconds_to_string(bonus[:award] || 0)}, код: #{bonus[:value]}" %>
                <% elsif (bonus[:award] || 0) < 0 %>
                  <%= "#{bonus[:name]}: штраф #{seconds_to_string(-(bonus[:award] || 0))}, код: #{bonus[:value]}" %>
                <% else %>
                  <%= "#{bonus[:name]}: виконано, код: #{bonus[:value]}" %>
                <% end %>
              </b>
            </p>
            <%= bonus[:help].html_safe unless bonus[:help].nil? %>
          <% elsif bonus[:missed] %>
            <p class="bonus-missed"><b><%= "#{bonus[:name]}: не виконано" %></b></p>
          <% elsif bonus[:delayed] %>
            <% unless game_passing.closed?(level) %>
              <div id="<%= "LevelBonusDelayCountdownContainer#{bonus[:id]}" %>" class="bonus-delay-timer">
                <%= bonus[:name] %> відкриється через <span id="<%= "LevelBonusDelayCountdownTimerText#{bonus[:id]}" %>">3 хвилини</span>
              </div>
              <div id="<%= "LevelBonusDelayCountdownLoadIndicator#{bonus[:id]}" %>" style="display: none;">Завантаження...</div>
              <br>
              <script>
                  LevelBonusDelayUpdater.setup({
                      initialCountdownValue: <%= bonus[:delay_for] %>,
                      gameId: <%= game_passing.game_id %>,
                      teamId: <%= team_id %>,
                      bonusId: <%= bonus[:id] %>,
                      bonusNum: <%= bonus[:position] %>,
                      levelId: <%= level.id %>
                  })
              </script>
            <% end %>
          <% elsif bonus[:limited] %>
            <% unless game_passing.closed?(level) %>
              <div id="<%= "LevelBonusLimitCountdownContainer#{bonus[:id]}" %>" class="bonus bonus-limit-timer">
                <%= bonus[:name] %> доступний <span id="<%= "LevelBonusLimitCountdownTimerText#{bonus[:id]}" %>">3 хвилини</span>
              </div>
              <div id="<%= "LevelBonusLimitCountdownLoadIndicator#{bonus[:id]}" %>" style="display: none;">Завантаження...</div>
              <br>
              <%= bonus[:task].html_safe unless bonus[:task].nil? %>
              <script>
                  LevelBonusLimitUpdater.setup({
                      initialCountdownValue: <%= bonus[:valid_for] %>,
                      gameId: <%= game_passing.game_id %>,
                      teamId: <%= team_id %>,
                      bonusId: <%= bonus[:id] %>,
                      bonusNum: <%= bonus[:position] %>,
                      levelId: <%= level.id %>
                  })
              </script>
            <% end %>
          <% else %>
            <p class="bonus"><b><%= bonus[:name] %></b></p>
            <%= bonus[:task].html_safe unless bonus[:task].nil? %>
          <% end %>
        </li>
        <br>
    <% end %>
  </ul>
</div>

app/views/game_passings/_hints.html.erb
<div id="LevelHintsContainer">
  <% hints_to_show.each_with_index do |hint, index| %>
    <div id="hint-<%= index + 1 %>">
      <fieldset>
        <legend>
          Підказка <%= index + 1 %> із <%= hints_to_show.count + upcoming_hints.count %>
        </legend>
        <%= hint.text.html_safe %>
      </fieldset>
    </div>
    <br>
  <% end %>

  <% upcoming_hints.each_with_index do |hint, index|  %>
    <div id="hint-<%= hints_to_show.count + index + 1 %>">
      <div id="<%= "LevelHintCountdownContainer#{hint.id}" %>" class="hint-timer">
        До підказки <%= hints_to_show.count + index + 1 %> лишилось <span id="<%= "LevelHintCountdownTimerText#{hint.id}" %>">3 хвилини</span>
      </div>
      <div id="<%= "LevelHintCountdownLoadIndicator#{hint.id}" %>" style="display: none;">Завантаження...</div>
      <script>
          LevelHintUpdater.setup({
              initialCountdownValue: <%= hint.available_in(begin_time) %>
              ,gameId: <%= game_passing.game_id %>, teamId: <%= team_id %>, hintId: <%= hint.id %>, hintNum: <%= index %>, levelId: <%= level.id %>
          })
      </script>
    </div>
    <br>
  <% end %>
</div>

app/views/game_passings/_linear.html.erb
<div id="updateButton"><%= link_to "Оновити", url_for("/play/#{game.id}?rnd=#{rand}") %></div>
<div id="statButton"><%= link_to "Cтатистика", url_for("/logs/short/#{game.id}?rnd=#{rand}"), target: :_blank%></div>
<br>
<br>
<div id="left-game-container">
  <%= form_tag("/play/#{game.id}", method: "post", remote: true, format: :js) do %>
    <br>Код:
    <%= text_field_tag(:answer, nil, autofocus: true, autocomplete: :off) %>
    <%= submit_tag " надіслати " %>
    <br>
  <% end %>
  <br>
  <div id="entered-code">
    <% unless answer.nil? || answer == '' %>
      <% if answer_was_correct? %>
        Код <span class="right_code"><%= answer %></span> вірний.<br><hr>
      <% else %>
        Код <span class="wrong_code"><%= answer %></span> невірний.<br><hr>
      <% end %>
    <% end %>
  </div>
  <br>
  <div id="entered-codes">
    <% entered_all_answers.each do |answer| %>
      <p><%= "#{answer[:time].strftime("%H:%M:%S")} #{answer[:user]} #{answer[:answer]}".html_safe %></p>
    <% end %>
  </div>
  <hr>
  <br>
</div>

<div id="main-game-container">
  <fieldset>
    <legend>
      <%= level.name %>
    </legend>

    <% if (level.complete_later || 0) > 0 %>
        <div id="LevelCompleteCountdownContainer" >До завершення рівня <span id="LevelCompleteCountdownTimerText">3 хвилини</span></div>

        <script>
            LevelCompleter.setup({
                initialCountdownValue: <%= (((game.game_type == 'selected' ? game_passing.current_level_position(team_id) : level.position) == 1 ? game.starts_at : game_passing.current_level_entered_at) - Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time).to_i + level.complete_later %>
                ,gameId: <%= game.id %>, levelId: <%= level.id %>, gameType: '<%= game.game_type %>', levelNumber: <%= game.game_type == 'selected' ? game_passing.current_level_position(team_id) : level.position %>
            })
        </script>
    <% end %>
    <br>

    <%= render 'messages', messages: level.messages %>
    <br><br>
    <%= render 'tasks', tasks: level.team_tasks(team_id) %>
    <br>

    <% team_questions = level.team_questions(team_id) %>
    <% if team_questions.count > 1 %>
      <div>
        <br>
        <b id="codes-closed">Вірних кодів <%= (game_passing.question_ids.to_set & team_questions.map(&:id).to_set).count %> із <%= team_questions.count %>:</b>
        <hr>
        <hr>
      </div>
    <% end %>
    <br>

    <%= render 'hints', upcoming_hints: upcoming_hints, hints_to_show: hints_to_show, begin_time: ((game.game_type == 'selected' ? game_passing.current_level_position(team_id) : level.position) == 1 ? game.starts_at : game_passing.current_level_entered_at), game_passing: game_passing, level: level, team_id: team_id %>
    <%= render 'penalty_hints', penalty_hints: penalty_hints, game_passing: game_passing, level: level, team_id: team_id %>

    <%= render level.olymp? ? 'olymp' : 'multy', sectors: sectors, level: level if sectors.count > 1 %>
    <hr>
    <br>
    <%= render 'bonuses', level: level, bonuses: bonuses, game_passing: game_passing, team_id: team_id if bonuses.count > 0 %>
    <br>
  </fieldset>
</div>
<%= subscribe_to "/game_passings/#{game_passing.id}/#{level.id}" %>
<%= subscribe_to "/game_passings/#{game_passing.id}/#{level.id}/answers" %>
<%= subscribe_to "/game_passings/#{game_passing.id}/#{level.id}/penalty_hints" %>

<script>
    PrivatePub.subscribe("/game_passings/<%= game_passing.id %>/<%= level.id %>", function(data, channel) {
        window.location.href = data.url;
    });

    PrivatePub.subscribe("/game_passings/<%= game_passing.id %>/<%= level.id %>/answers", function(data, channel) {
        let answers = data.answers || [];
        for (let i = 0; i < answers.length; i++) {
            $('#entered-codes').prepend($('<p>' + answers[i].time + ' ' + answers[i].user + ' ' + answers[i].answer + '</p>'));
        }
        let sectors = data.sectors || [];
        for (let i = 0; i < sectors.length; i++) {
            let sector = $('#sector-' + sectors[i].position).get(0);
            <% if level.olymp? %>
              sector.innerHTML = sectors[i].value;
            <% else %>
              sector.innerHTML = sectors[i].name + ': ' + sectors[i].value;
            <% end %>
        }
        let bonuses = data.bonuses || [];
        for (let i = 0; i < bonuses.length; i++) {
            // let bonus = $('#bonus-' + bonuses[i].id).get(0);
            let elem = '<li id="bonus-' + bonuses[i].id + '">';
            elem += '<p class="bonus-answered"><b>' + (bonuses[i].award != "" ? (bonuses[i].name + ': нагорода ' + bonuses[i].award) : (bonuses[i].name + ': виконано')) + ', код: ' + bonuses[i].value +'</b></p>';
            if (bonuses[i].help) elem += bonuses[i].help;
            elem += '</li>';
            // bonus.innerHTML = elem;
            $('#bonus-' + bonuses[i].id).replaceWith(elem);
        }
        let needed = data.needed || 0;
        let closed = data.closed || 0;
        if (needed > 0 && closed > 0) {
            $('#codes-closed').get(0).innerHTML = 'Вірних кодів ' + closed + ' із ' + needed + ':';
        }

    });

    PrivatePub.subscribe("/game_passings/<%= game_passing.id %>/<%= level.id %>/penalty_hints", function(data, channel) {
        let hint = data.hint || {};
        let hint_block = $('#penalty-hint-' + hint.id + ' .penalty-hint-body').get(0);
        hint_block.innerHTML = hint.text;
    });

    $(document).on("ajax:error", 'body', function(e, data, status) {
        if (data.status == 0) {
            $('#entered-code').get(0).innerHTML = '<span class="wrong_code">проблема мережі</span>';
        }
    });
</script>

app/views/game_passings/_messages.html.erb
<div id="LevelMessagesContainer">
  <% messages.each do |message| %>
    <div id="message-<%= message.id %>" class="author_message">
      <%= "Повідомлення від #{message.user.nickname}: #{message.text}".html_safe %>
    </div>
    <br>
  <% end %>
</div>

app/views/game_passings/_multy.html.erb
<div id="LevelSectorsContainer">
  <ul>
    <% sectors.each do |sector| %>
        <li id="sector-<%= sector[:position] %>"><%= "#{sector[:name]}: #{sector[:value]}".html_safe %></li>
    <% end %>
  </ul>
</div>

app/views/game_passings/_tasks.html.erb
<div id="LevelTasksContainer">
  <% tasks.each do |task| %>
    <div id="task-<%= task.id %>">
      <%= task.text.html_safe %>
    </div>
    <br>
<% end %>
</div>

app/views/game_passings/show_current_level.html.erb
<h2>
  "<strong><%= game.name %></strong>"
  <br>
  Завдання <%= game.game_type == 'selected' ? game_passing.current_level_position(team_id) : level.position %> із <%= game.levels.count %>
</h2>
<br>

<%= render game.game_type == 'panic' ? 'panic' : 'linear',
           game_passing: game_passing,
           game: game,
           team_id: team_id,
           level: level,
           entered_all_answers: entered_all_answers,
           bonuses: bonuses,
           sectors: sectors,
           penalty_hints: penalty_hints,
           upcoming_hints: upcoming_hints,
           hints_to_show: hints_to_show,
           answer: answer
%>

<!--
<% if current_user.captain? %>
    <%#= link_to "Зійти з дистанції", url: "game_passings/exit_game/#{@game_passing.game_id}" %>
<% end %>
-->
<% if game.is_testing? %>
  <br>
  <%= link_to "Завершити тестування", finish_test_game_path(game), method: :post %>
<% end %>