config/routes.rb
Rails.application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root 'games#index'

  resources :teams

  resources :invitations do
    post 'accept', on: :member
    post 'reject', on: :member
  end

  resources :team_requests do
    post 'accept', on: :member
    post 'reject', on: :member
  end

  resources :users do
    resources :games
  end

  resources :games do
    resources :levels do
      resources :tasks
      resources :hints do
        post 'copy', on: :member
      end
      resources :penalty_hints do
        post 'copy', on: :member
      end
      resources :questions do
        resources :answers
        collection do
          get  :new_batch
          post :create_batch
        end
        post 'move_up', on: :member
        post 'move_down', on: :member
        post 'copy', on: :member
        post 'copy_to_bonus', on: :member
      end
      resources :bonuses do
        resources :bonus_answers
        collection do
          get  :new_batch
          post :create_batch
        end
        post 'move_up', on: :member
        post 'move_down', on: :member
        post 'copy', on: :member
        post 'copy_to_sector', on: :member
      end
      resources :messages
      collection do
        patch :sort
      end
      post 'move_up', on: :member
      post 'move_down', on: :member
      post 'change_position', on: :member
      post 'copy', on: :member
      post 'dismiss', on: :member
      post 'undismiss', on: :member
      post 'add_answer_to_sectors', on: :member
      post 'add_answer_to_bonuses', on: :member
    end
    resources :game_bonuses
    get 'show_scenario', on: :member
    get 'new_level_order', on: :member
    post 'create_level_order', on: :member
    post 'end_game', on: :member
    post 'open_game', on: :member
    post 'start_test', on: :member
    post 'finish_test', on: :member
  end

  match '/game_entries/recall/:id', to: 'game_entries#recall', via: 'post'
  match '/game_entries/reopen/:id', to: 'game_entries#reopen', via: 'post'
  match '/game_entries/cancel/:id', to: 'game_entries#cancel', via: 'post'
  match '/game_entries/accept/:id', to: 'game_entries#accept', via: 'post'
  match '/game_entries/reject/:id', to: 'game_entries#reject', via: 'post'
  match '/game_entries/reaccept/:id', to: 'game_entries#reaccept', via: 'post'
  match '/game_entries/new/:game_id/:team_id',  to: 'game_entries#new', via: 'post'

  match '/game_passings/show_results', to: 'game_passings#show_results', via: 'get'
  match '/play/:game_id/tip', to: 'game_passings#get_current_level_tip', via: 'get'
  match '/play/:game_id', to: 'game_passings#show_current_level', via: 'get'
  match '/play/:game_id', to: 'game_passings#post_answer', via: 'post'
  match '/play/:game_id/autocomplete_level', to: 'game_passings#autocomplete_level', via: 'get'
  match '/play/:game_id/penalty_hint', to: 'game_passings#use_penalty_hint', via: 'post'
  match '/play/:game_id/penalty_hint', to: 'game_passings#show_penalty_hint', via: 'get'
  match '/play/:game_id/bonus', to: 'game_passings#get_current_level_bonus', via: 'get'
  match '/play/:game_id/miss_bonus', to: 'game_passings#miss_current_level_bonus', via: 'post'

  match '/stats/:action/:game_id', to: 'game_passings#index', via: 'get'
  match '/logs/livechannel/:game_id', to: 'logs#show_live_channel', via: 'get'
  match '/logs/level/:game_id/:team_id', to: 'logs#show_level_log', via: 'get'
  match '/logs/game/:game_id/:team_id', to: 'logs#show_game_log', via: 'get'
  match '/logs/full/:game_id', to: 'logs#show_full_log', via: 'get'
  match '/logs/short/:game_id', to: 'logs#show_short_log', via: 'get'
  match '/logs/special/:game_id', to: 'logs#show_special_results', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/dashboard', to: 'dashboard#index',         via: 'get'
  match '/team-room', to: 'team_room#index',         via: 'get'

  match '/teams/edit/delete_member', to: 'teams#delete_member', via: 'post'
  match '/teams/edit/captain', to: 'teams#make_member_captain', via: 'post'
  match '/teams/edit/leave_team', to: 'teams#leave_team', via: 'post'
  match '/tinymce_assets', to: 'tinymce_assets#create', via: 'post'
  match '/help', to: 'help#index', via: 'get'
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :level
  belongs_to :team

  scope :of_team, ->(team_id) { where('team_id IS NULL OR team_id = ?', team_id) }

  def delay_in_minutes
    delay.nil? ? nil : delay / 60
  end

  def delay_in_minutes=(value)
    self.delay = value.to_i * 60
  end

  def ready_to_show?(current_level_entered_at)
    seconds_passed = Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time - current_level_entered_at
    seconds_passed >= delay
  end

  def available_in(current_level_entered_at)
    (current_level_entered_at - Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time).to_i + delay
  end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  before_action :find_level
  before_action :find_game
  before_action :ensure_game_was_not_finished, except: [:show]
  before_action :find_hint, only: [:edit, :update, :destroy, :copy]
  before_action :find_teams, only: [:new, :edit, :create, :update]

  before_action :ensure_author
  before_action :ensure_game_was_not_started, only: [:new, :create, :edit, :update]

  def new
    @hint = @level.hints.build
  end

  def create
    @hint = @level.hints.build(hint_params)
    if @hint.save
      redirect_to game_level_path(@game, @level, anchor: "hint-#{@hint.id}")
    else
      render 'new'
    end
  end

  def edit
    render
  end

  def update
    if @hint.update_attributes(hint_params)
      redirect_to game_level_path(@level.game, @level, anchor: "hint-#{@hint.id}")
    else
      render 'edit'
    end
  end

  def destroy
    @hint.destroy
    redirect_to game_level_path(@level.game, @level, anchor: "hints-block")
  end

  def copy
    @new_hint = @hint.dup
    if @new_hint.save
      redirect_to game_level_path(@game, @level, anchor: "hint-#{@new_hint.id}")
    else
      redirect_to game_level_path(@game, @level, anchor: "hint-#{@hint.id}")
    end
  end

  protected

  def hint_params
    params.require(:hint).permit(:level_id, :text, :delay, :team_id)
  end

  def find_level
    @level = Level.find(params[:level_id])
  end

  def find_game
    @game = @level.game
  end

  def find_hint
    @hint = Hint.find(params[:id])
  end

  def find_teams
    @teams = [['Для всіх', nil]] + GameEntry.of_game(@game.id).where("status in ('new', 'accepted')").includes(:team).map do |game_entry|
      team = game_entry.team
      [team.name, team.id]
    end
  end

end

app/views/hints/_form.html.erb
<%= tinymce language: 'uk' %>
<div class="form-group row">
  <%= f.label "Команда", class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.select(:team_id, teams, {}, { class: 'form-control' }) %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :text, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.text_area :text, class: 'tinymce' %>
  </div>
</div>
<div class="form-group row">
  <%= f.label "Через", class: 'col-sm-2 col-form-label' %>
  <div id="hint-delay-form" class="col-sm-10 form-inline">
    <%= render 'shared/time_form' %>
    <%= f.hidden_field :delay%>
  </div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
        set_time_form(parseInt($('#hint_delay').val()), '#hint-delay-form');

        $('#hint-delay-form .time-hours').on('change', function() {
            set_field_time('#hint_delay', '#hint-delay-form', 1);
        });

        $('#hint-delay-form .time-minutes').on('change', function() {
            set_field_time('#hint_delay', '#hint-delay-form', 1);
        });

        $('#hint-delay-form .time-seconds').on('change', function() {
            set_field_time('#hint_delay', '#hint-delay-form', 1);
        });
    });
</script>

app/views/hints/_list.html.erb
<% unless hints.empty? %>
    <% hints.each do |hint| %>
        <fieldset id="hint-<%= hint.id %>">
          <legend>
            <% if hint.team.nil? %>
                <em>Для всіх</em>:
            <% else %>
                <em>Для </em> <strong><%= link_to hint.team.name, team_path(hint.team) %></strong>:
            <% end %>
            <% unless game.author_finished? %>
              <em>
                <%= link_to "(редагувати)", edit_game_level_hint_path(game, level, hint) %>
                <%= link_to "(видалити)", game_level_hint_path(game, level, hint), method: :delete, data: { confirm: 'Ви впевнені?' } %>
                <%= link_to "(скопіювати)", copy_game_level_hint_path(game, level, hint), method: :post %>
              </em>
            <% end %>
          </legend>
          <p>
            <em>Через</em> <strong><%= seconds_to_string(hint.delay || 0) %></strong> <em>:</em>
          </p>
          <p>
            <%= hint.text.html_safe %>
          </p>
        </fieldset>
    <% end %>
<% end %>

app/views/hints/edit.html.erb
<p>
  Редагування підказки до завдання "<%= link_to @level.name, game_level_path(@game, @level) %>" гри "<%= link_to @game.name, game_path(@game) %>"
</p>

<br>

<%= form_for @hint, url: game_level_hint_path(@game, @level, @hint) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>  
  <%= render 'form', f: f, teams: @teams %>
  <%= f.submit "Редагувати", class: 'btn btn-light' %>
  <em><%= link_to "(відмінити)", game_level_path(@game, @level, anchor: "hint-#{@hint.id}") %></em>
<% end %>

app/views/hints/new.html.erb
<p>
    Нова підказка до завдання "<%= link_to @level.name, game_level_path(@game, @level) %>" гри "<%= link_to @game.name, game_path(@game) %>"
</p>

<br>

<%= form_for @hint, url: game_level_hints_path(@game, @level) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>  
  
  <%= render 'form', f: f, teams: @teams %>

  <%= f.submit "Додати підказку", class: 'btn btn-light' %>
  <em><%= link_to "(відмінити)", game_level_path(@game, @level, anchor: "hints-block") %></em>
<% end %>