config/routes.rb
Rails.application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root 'games#index'

  resources :teams

  resources :invitations do
    post 'accept', on: :member
    post 'reject', on: :member
  end

  resources :team_requests do
    post 'accept', on: :member
    post 'reject', on: :member
  end

  resources :users do
    resources :games
  end

  resources :games do
    resources :levels do
      resources :tasks
      resources :hints do
        post 'copy', on: :member
      end
      resources :penalty_hints do
        post 'copy', on: :member
      end
      resources :questions do
        resources :answers
        collection do
          get  :new_batch
          post :create_batch
        end
        post 'move_up', on: :member
        post 'move_down', on: :member
        post 'copy', on: :member
        post 'copy_to_bonus', on: :member
      end
      resources :bonuses do
        resources :bonus_answers
        collection do
          get  :new_batch
          post :create_batch
        end
        post 'move_up', on: :member
        post 'move_down', on: :member
        post 'copy', on: :member
        post 'copy_to_sector', on: :member
      end
      resources :messages
      collection do
        patch :sort
      end
      post 'move_up', on: :member
      post 'move_down', on: :member
      post 'change_position', on: :member
      post 'copy', on: :member
      post 'dismiss', on: :member
      post 'undismiss', on: :member
      post 'add_answer_to_sectors', on: :member
      post 'add_answer_to_bonuses', on: :member
    end
    resources :game_bonuses
    get 'show_scenario', on: :member
    get 'new_level_order', on: :member
    post 'create_level_order', on: :member
    post 'end_game', on: :member
    post 'open_game', on: :member
    post 'start_test', on: :member
    post 'finish_test', on: :member
  end

  match '/game_entries/recall/:id', to: 'game_entries#recall', via: 'post'
  match '/game_entries/reopen/:id', to: 'game_entries#reopen', via: 'post'
  match '/game_entries/cancel/:id', to: 'game_entries#cancel', via: 'post'
  match '/game_entries/accept/:id', to: 'game_entries#accept', via: 'post'
  match '/game_entries/reject/:id', to: 'game_entries#reject', via: 'post'
  match '/game_entries/reaccept/:id', to: 'game_entries#reaccept', via: 'post'
  match '/game_entries/new/:game_id/:team_id',  to: 'game_entries#new', via: 'post'

  match '/game_passings/show_results', to: 'game_passings#show_results', via: 'get'
  match '/play/:game_id/tip', to: 'game_passings#get_current_level_tip', via: 'get'
  match '/play/:game_id', to: 'game_passings#show_current_level', via: 'get'
  match '/play/:game_id', to: 'game_passings#post_answer', via: 'post'
  match '/play/:game_id/autocomplete_level', to: 'game_passings#autocomplete_level', via: 'get'
  match '/play/:game_id/penalty_hint', to: 'game_passings#use_penalty_hint', via: 'post'
  match '/play/:game_id/penalty_hint', to: 'game_passings#show_penalty_hint', via: 'get'
  match '/play/:game_id/bonus', to: 'game_passings#get_current_level_bonus', via: 'get'
  match '/play/:game_id/miss_bonus', to: 'game_passings#miss_current_level_bonus', via: 'post'

  match '/stats/:action/:game_id', to: 'game_passings#index', via: 'get'
  match '/logs/livechannel/:game_id', to: 'logs#show_live_channel', via: 'get'
  match '/logs/level/:game_id/:team_id', to: 'logs#show_level_log', via: 'get'
  match '/logs/game/:game_id/:team_id', to: 'logs#show_game_log', via: 'get'
  match '/logs/full/:game_id', to: 'logs#show_full_log', via: 'get'
  match '/logs/short/:game_id', to: 'logs#show_short_log', via: 'get'
  match '/logs/special/:game_id', to: 'logs#show_special_results', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/dashboard', to: 'dashboard#index',         via: 'get'
  match '/team-room', to: 'team_room#index',         via: 'get'

  match '/teams/edit/delete_member', to: 'teams#delete_member', via: 'post'
  match '/teams/edit/captain', to: 'teams#make_member_captain', via: 'post'
  match '/teams/edit/leave_team', to: 'teams#leave_team', via: 'post'
  match '/tinymce_assets', to: 'tinymce_assets#create', via: 'post'
  match '/help', to: 'help#index', via: 'get'
end

app/models/game.rb
class Game < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  MAX_TEAMS_COUNT = 10_000

  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :authors, class_name: 'User', join_table: 'games_authors', foreign_key: 'game_id', association_foreign_key: 'author_id'
  has_many :levels, -> { order(:position) }
  has_many :level_orders
  has_many :logs, -> { order(:time) }
  has_many :game_entries, class_name: 'GameEntry'
  has_many :game_passings, class_name: 'GamePassing'
  has_many :game_bonuses, class_name: 'GameBonus', dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :bonuses, -> { order(:position) }, dependent: :destroy

  delegate :nickname, :telegram, to: :author, prefix: true

  validates_presence_of :name,
                        message: 'Не введено назву гри'

  validates_presence_of :starts_at,
                        message: 'Не введено дату старту гри'

  validates_uniqueness_of :name,
                          message: 'Гра з такою назвою уже існує'

  validates_presence_of :description,
                        message: 'Не введено опис гри'

  validates_numericality_of :max_team_number,
                            greater_than_or_equal_to: 0,
                            less_than_or_equal_to: MAX_TEAMS_COUNT, allow_nil: true,
                            message: 'Не коректно вказано обмеження на кількість команд у грі'

  validates_presence_of :author

  #validate :game_starts_in_the_future
  validate :valid_max_num

  # validate :deadline_is_in_future
  # validate :deadline_is_before_game_start

  before_save do
    if !draft? && topic_id.nil?
      topic_name = "#{name} (#{starts_at.strftime('%H:%M %d.%m.%Y')})"
      topic = Forem::Forum.where(name: "#{game_size || 'Лайт'}и").first.topics.build(subject: topic_name, user: author, posts_attributes: [text: topic_name])
      topic.save!
      self.topic_id = topic.id
    end
  end

  scope :by, -> (author_id) { where(author_id: author_id) }
  scope :non_drafts, -> { where(is_draft: false) }
  scope :finished, -> { where('author_finished_at IS NOT NULL') }

  def slug_candidates
    [
      [:transliterated_name, :id]
    ]
  end

  def transliterated_name
    require 'ee_strings.rb'
    I18n.transliterate(self.name.downcase_utf8_cyr)
  end

  def self.started
    Game.order(starts_at: :desc).all.select(&:started?)
  end

  def draft?
    self.is_draft
  end

  def started?
    (self.starts_at.nil? ? false : Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time) > (self.is_testing? ? self.test_date : self.starts_at)
  end

  def created_by?(user)
    user.author_of?(self)
  end

  def finished_teams
    GamePassing.of_game(id).finished.map(&:team)
  end

  def place_of(team)
    game_passing = GamePassing.of(team.id, id)
    return nil unless game_passing && (game_passing.finished? || self.game_type == 'panic')
    if self.game_type == 'linear' || game_passing.finished_at
      count_of_finished_before =
        GamePassing.of_game(id).finished_before(game_passing.finished_at).count
    else
      count_of_finished = GamePassing.finished.count
      count_of_finished_before = count_of_finished +
        GamePassing.of_game(id).select do |game_pass|
          !game_passing.finished_at &&
          game_pass.closed_levels.count > game_passing.closed_levels.count ||
          game_pass.closed_levels.count == game_passing.closed_levels.count &&
          game_pass.current_level_entered_at < game_passing.current_level_entered_at
        end.count
    end
    count_of_finished_before + 1
  end

  def self.notstarted
    Game.all.order(starts_at: :asc).select { |game| !game.draft? && !game.started? }
  end

  def free_place_of_team!
    if self.requested_teams_number > 0
      self.requested_teams_number -= 1
      save
    end
  end

  def reserve_place_for_team!
    self.requested_teams_number += 1
    save
  end

  def can_request?
    self.max_team_number.nil? || self.requested_teams_number < self.max_team_number
    Game.all.select { |game| !game.started? }
  end

  def finish_game!
    self.create_results
    self.author_finished_at = Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time
    self.save!
  end

  def open_game!
    self.author_finished_at = nil
    self.save!
  end

  def author_finished?
    !self.author_finished_at.nil?
  end

  def is_testing?
    self.is_testing
  end

  def start_test!(team_id)
    self.is_testing = 't'
    self.test_date = self.starts_at
    self.starts_at = Time.zone.now + 0.1.second
    self.registration_deadline = nil
    self.tested_team_id = team_id
    self.save!
  end

  def stop_test!
    self.is_testing = 'f'
    self.starts_at = self.test_date
    self.test_date = Time.zone.now
    self.tested_team_id = nil
    self.save!

    game_passing = GamePassing.of_game(id)
    logs = Log.of_game(id)
    game_bonuses = GameBonus.of_game(id)
    closed_levels = ClosedLevel.of_game(id)
    game_passing.each do |elem|
      elem.questions.clear
      elem.bonuses.clear
    end

    game_passing.delete_all
    logs.delete_all
    game_bonuses.delete_all
    closed_levels.delete_all
  end

  def create_results
    game_bonuses = GameBonus.of_game(id).select("team_id, sum(award) as sum_bonuses").group(:team_id).to_a
    game_passings = GamePassing.of_game(id).includes(:team)
    if game_type == 'panic'
      game_finished_at = starts_at + duration * 60
      game_results = game_passings.map do |game_passing|
        team_bonus = game_bonuses.select{ |bonus| bonus.team_id == game_passing.team_id}
        {
            team_id: game_passing.team_id,
            team_name: game_passing.team_name,
            finished_at: game_passing.finished_at || game_finished_at,
            closed_levels: game_passing.closed_levels.count,
            sum_bonuses: (game_passing.sum_bonuses || 0) + (team_bonus.empty? ? 0 : team_bonus[0].sum_bonuses)
        }
      end.sort do |a, b|
        (a[:finished_at] - a[:sum_bonuses]) <=> (b[:finished_at] - b[:sum_bonuses])
      end
    else
      current_time = Time.now
      game_results = game_passings.map do |game_passing|
        team_bonus = game_bonuses.select{ |bonus| bonus.team_id == game_passing.team_id}
        {
            team_id: game_passing.team_id,
            team_name: game_passing.team_name,
            finished_at: game_passing.finished_at,
            closed_levels: game_passing.closed_levels.count,
            sum_bonuses: (game_passing.sum_bonuses || 0) + (team_bonus.empty? ? 0 : team_bonus[0].sum_bonuses),
            exited: game_passing.exited?
        }
      end.sort_by do |v|
        [-v[:closed_levels], (v[:finished_at] || current_time) - v[:sum_bonuses]]
      end
    end
    Result.delete_all(game_id: id)
    game_results.each_with_index do |result, index|
      Result.create!(game_id: id, team_id: result[:team_id], place: result[:finished_at].nil? && !game_type == 'panic' ? -1 : (index + 1))
    end
  end

  protected

  def game_starts_in_the_future
    if self.author_finished_at.nil? && self.starts_at && self.starts_at < Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time
      errors.add(:starts_at, 'Вибрано дату із минулого.')
    end
  end

  def valid_max_num
    if self.max_team_number
      if self.max_team_number < self.requested_teams_number
        errors.add(:max_team_number, 'Кількість команд, що подали заявку, перевищує дозволене число')
      end
    end
  end

  def deadline_is_in_future
    if self.author_finished_at.nil? && self.registration_deadline &&
        self.registration_deadline < Time.zone.now.strftime("%d.%m.%Y %H:%M:%S.%L").to_time
      errors.add(:registration_deadline, 'Вказано кінцевий термін реєстрації із минулого')
    end
  end

  def deadline_is_before_game_start
    if self.registration_deadline &&
       self.starts_at && self.registration_deadline > self.starts_at
      errors.add(:registration_deadline, 'Вказано кінцевий термін реєстрації пізніший дати початку гри')
    end
  end


end

app/controllers/bonuses_controller.rb
class BonusesController < ApplicationController
  before_action :find_game
  before_action :ensure_game_was_not_finished, except: [:show]
  before_action :ensure_author
  before_action :find_level
  before_action :find_bonus, only: [:edit, :update, :move_up, :move_down, :destroy, :copy, :copy_to_sector]
  before_action :find_teams, only: [:new, :edit, :create, :update, :new_batch, :create_batch]

  def new
    @bonus = @game.bonuses.build(name: "Бонус #{@level.bonuses.count + 1}")
    @bonus.bonus_answers.build
    render :new, locals: {teams: @teams, game: @game, bonus: @bonus, level: @level}
  end

  def create
    params[:bonus][:level_ids] ||= [@level.id]
    @bonus = @game.bonuses.build(bonus_params)
    if @bonus.save
      redirect_to game_level_path(@game, @level, anchor: "bonus-#{@bonus.id}")
    else
      render :new,  locals: {teams: @teams, game: @game, bonus: @bonus, level: @level}
    end
  end

  def new_batch
    @bonus = @game.bonuses.build(name: "Бонус")
    render :new_batch, locals: {teams: @teams, game: @game, bonus: @bonus, level: @level}
  end

  def create_batch
    params[:bonus][:level_ids] ||= [@level.id]
    answers_list = bonus_params[:answers_list].split(/\n+/)
    answers_list.each do |answers|
      all_answers = answers.split(';')
      bonus = @game.bonuses.build(bonus_params.to_hash.merge({ name: "#{bonus_params[:name]} #{@level.bonuses.count + 1}" }))
      all_answers.each do |answer|
        bonus.bonus_answers.build(value: answer, team_id: bonus_params[:team_id])
      end
      bonus.save!
    end
    redirect_to game_level_path(@level.game, @level, anchor: "bonuses-block")
  end

  def edit
    render :edit, locals: {teams: @teams, game: @game, bonus: @bonus, level: @level}
  end

  def show
    redirect_to game_level_path(@level.game, @level)
  end

  def update
    params[:bonus][:level_ids] ||= [@level.id]
    if @bonus.update_attributes(bonus_params)
      redirect_to game_level_path(@game, @level, anchor: "bonus-#{@bonus.id}")
    else
      render :edit,  locals: {teams: @teams, game: @game, bonus: @bonus, level: @level}
    end
  end

  def destroy
    @bonus.destroy
    redirect_to game_level_path(@game, @level, anchor: "bonuses-block")
  end

  def move_up
    @bonus.move_higher
    redirect_to game_level_path(@game, @level, anchor: "bonus-#{@bonus.id}")
  end

  def move_down
    @bonus.move_lower
    redirect_to game_level_path(@game, @level, anchor: "bonus-#{@bonus.id}")
  end

  def copy
    @new_bonus = @bonus.dup
    @new_bonus.name = "Бонус #{@level.bonuses.count + 1}"
    @new_bonus.set_list_position(@game.bonuses.count + 1)
    @bonus.bonus_answers.each do |answer|
      new_answer = answer.dup
      new_answer.bonus_id = nil
      @new_bonus.bonus_answers << new_answer
    end
    @bonus.levels.each do |level|
      @new_bonus.levels << level
    end
    if @new_bonus.save
      redirect_to game_level_path(@level.game, @level, anchor: "bonus-#{@new_bonus.id}")
    else
      flash[:notice] = 'ERROR: Item can\'t be cloned.'
      redirect_to game_level_path(@level.game, @level, anchor: "bonus-#{@bonus.id}")
    end
  end

  def copy_to_sector
    @new_question = @level.questions.build(name: "Сектор #{@level.questions.count + 1}")
    @new_question.set_list_position(@level.questions.count + 1)
    @bonus.bonus_answers.each do |answer|
      @new_question.answers.build(value: answer.value, team_id: answer.team_id)
    end
    if @new_question.save
      redirect_to game_level_path(@level.game, @level, anchor: "question-#{@new_question.id}")
    else
      p @new_question.errors
      flash[:notice] = 'ERROR: Item can\'t be cloned.'
      redirect_to game_level_path(@level.game, @level, anchor: "bonus-#{@bonus.id}")
    end
  end

  protected

  def bonus_params
    params.require(:bonus).permit(
        :name, :task, :help, :award_time, :correct_answer, :team_id,
        :is_absolute_limited, :valid_from, :valid_to, :is_delayed,
        :delay_for, :is_relative_limited, :valid_for,
        :answers_list, level_ids: [],
        bonus_answers_attributes: [:id, :value, :team_id, :_destroy])
  end

  def find_game
    @game = Game.friendly.find(params[:game_id])
  end

  def find_level
    @level = Level.find(params[:level_id])
  end

  def find_bonus
    @bonus = Bonus.find(params[:id])
  end

  def find_teams
    @teams = [['Для всіх', nil]] + GameEntry.of_game(@game.id).where("status in ('new', 'accepted')").includes(:team).map do |game_entry|
      team = game_entry.team
      [team.name, team.id]
    end
  end
end

app/views/bonuses/_bonus_answer_fields.html.erb
<br>
<div class="nested-fields">
  <div>
    <%= link_to_remove_association 'Видалити відповідь', f, class: 'btn btn-outline-danger btn-sm' %>
  </div>
  <div class="form-group row">
    <%= f.label "Команда", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.select(:team_id, teams, {}, { class: 'form-control form-control-sm' }) %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label "Відповідь", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :value, class: 'form-control form-control-sm' %>
    </div>
  </div>
</div>

app/views/bonuses/_list.html.erb
<% bonuses.each do |bonus| %>
  <div id="bonus-<%= bonus.id %>">
    <fieldset>
      <legend>
        <% if bonus.team.nil? %>
          <em>Для всіх</em>:
        <% else %>
          <em>Для </em> <strong><%= link_to bonus.team.name, team_path(bonus.team) %></strong>:
        <% end %>
        <% unless game.author_finished? %>
          <em>
            <%= link_to "(редагувати)", edit_game_level_bonus_path(game, level, bonus) %>
            <%= link_to "(видалити)", game_level_bonus_path(game, level, bonus), method: :delete, data: { confirm: 'Ви впевнені?' } %>
            <%= link_to "(скопіювати)", copy_game_level_bonus_path(game, level, bonus), method: :post %>
            <%= link_to "(скопіювати в сектор)", copy_to_sector_game_level_bonus_path(game, level, bonus), method: :post %>
          </em>
        <% end %>
      </legend>
      <p>
        <strong><%= bonus.name %>:</strong>
      </p>
      <% unless bonus.task.nil? %>
        <p>
          <strong>Завдання: </strong><%= bonus.task.html_safe %>
        </p>
      <% end %>
      <% unless bonus.help.nil? %>
        <p>
          <strong>Підказка: </strong><%= bonus.help.html_safe %>
        </p>
      <% end %>
      <% if (bonus.award_time || 0) > 0 %>
        <p>
          <strong>Винагорода: </strong><%= seconds_to_string(bonus.award_time || 0) %>
        </p>
      <% end %>
      <% if (bonus.award_time || 0) < 0 %>
        <p>
          <strong>Штраф: </strong><%= seconds_to_string(-(bonus.award_time || 0)) %>
        </p>
      <% end %>
      <% if bonus.is_absolute_limited? %>
        <p>
          <strong>Обмежити час доступності: </strong>
          <%= bonus.valid_from.nil? ? '' : " з #{bonus.valid_from.strftime("%d.%m.%Y %H:%M")}" %>
          <%= bonus.valid_to.nil? ? '' : " по #{bonus.valid_to.strftime("%d.%m.%Y %H:%M")}" %>
        </p>
      <% end %>
      <% if bonus.is_delayed? %>
        <p>
          <strong>Обмежити час появи: </strong>
          <%= "на #{seconds_to_string(bonus.delay_for || 0)}" %>
        </p>
      <% end %>
      <% if bonus.is_relative_limited? %>
        <p>
          <strong>Обмежити час виконання: </strong>
          <%= "на #{seconds_to_string(bonus.valid_for || 0)}" %>
        </p>
      <% end %>
      <% bonus.bonus_answers.each do |answer| %>
        <p>
          <span class="bonus"><%= answer.value %></span>
          <% if answer.team.nil? %>
            <em> (для всіх)</em>
          <% else %>
            <em> (для </em> <strong><%= link_to answer.team.name, team_path(answer.team) %></strong>)
          <% end %>
        </p>
      <% end %>
    </fieldset>
  </div>
  <br>
<% end %>

app/views/bonuses/edit.html.erb
<h2>
  Завдання "<strong><%= link_to level.name, game_level_path(game, level) %></strong>"
</h2>

<p>
  <em>(гра "<%= link_to game.name, game_path(game) %>")</em>
</p>

<br>

<%= form_for bonus, url: game_level_bonus_path(game, level, bonus) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= render 'form', f: f, teams: teams, game: game, bonus: bonus %>
  <%= f.submit "Змінити", class: 'btn btn-light' %>
  <em><%= link_to "(відмінити)", game_level_path(game, level, anchor: "bonus-#{bonus.id}") %></em>
<% end %>

app/views/bonuses/new.html.erb
<h2>
  Завдання "<strong><%= link_to level.name, game_level_path(game, level) %></strong>"
</h2>

<p>
  <em>(гра "<%= link_to game.name, game_path(game) %>")</em>
</p>

<br>

<%= form_for bonus, url: game_level_bonuses_path(game, level) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= render 'form', f: f, teams: teams, game: game, bonus: bonus %>
  <%= f.submit "Додати бонус", class: 'btn btn-light' %>
  <em><%= link_to "(відмінити)", game_level_path(game, level, anchor: "bonuses-block") %></em>
<% end %>